name: portal
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7.10
  - pytorch=1.8.1
  - scanpy=1.7.2
  - anndata=0.7.6
  - scikit-learn=0.24.1
  - numpy=1.19.2
  - scipy==1.6.2
  - scikit-learn==0.24.1
  - statsmodels==0.12.2
  - louvain==0.7.0
  - leidenalg==0.7.0
  - pandas=1.1.5
  - umap-learn=0.4.6
  - numba=0.49.1
  - pytables=3.6.1
  - scikit-misc=0.1.3
  - rpy2=3.4.5
  - anndata2ri=1.0.6