name: portal
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7.10
  - pytorch=1.8.1
  - scanpy=1.7.2
  - anndata=0.7.6
  - scikit-learn=0.24.1
  - numpy=1.19.2
  - pandas=1.1.5
  - umap-learn=0.4.6
  - tables=3.6.1
  - rpy2=3.4.5
  - anndata2ri=1.0.6